### ISSUE TITLE
Easily breakable, please do not use

### ISSUE THREAD

**Issue by luk2302** [aykutkardas/tardiness.js#1]
A colleague of yours posted the link to this on SO (https://stackoverflow.com/q/67211470/2442804). I discouraged the usage of this script in the comments already but feel like I should tell it to you as well. Please do not use this in any of your products, calling this encryption is a real stretch. In general building your own crypto is a very bad idea unless you know very, very well what you are doing and have years of crypto experience.

To demonstrate the issue: If I have a single cleartext + ciphertext pair I can extract the key and decrypt all other "encrypted" data:

```
function extractKey(cleartext, ciphertext) {
    for (let i = 0; i < cleartext.length; i++) {
        console.log(String.fromCharCode(ciphertext.charCodeAt(i) - cleartext.charCodeAt(i))); // this prints the chars of the original "very_secret_key"
    }
}

very_secret_key = "something";
clear = "abcdefghijklmnopqrstuvwxyz";
cipher = tardiness.crypto(clear, very_secret_key);
extractKey(clear, cipher)
```

**Comment by aykutkardas** [comment]
You're right, I didn't make this an npm package and thought it wouldn't be used. I added a warning though. Thank you very much for the information you have provided. This was just a test project for me. @luk2302 

**Related commit:** https://github.com/aykutkardas/tardiness.js/commit/a421f92f58c65514fe0a720a71f85030a8e18791
